# name: Build, Push, and Deploy
# 
# on:
#   push:
#     branches: [ main ]  # Trigger the workflow on push to main branch
#   workflow_dispatch:    # Allow manual trigger
# 
# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}
# 
# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
# 
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3
# 
#     - name: Log in to the Container registry
#       uses: docker/login-action@v2
#       with:
#         registry: ${{ env.REGISTRY }}
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
# 
#     - name: Extract metadata (tags, labels) for Docker
#       id: meta
#       uses: docker/metadata-action@v4
#       with:
#         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
# 
#     - name: Build and push Docker image
#       uses: docker/build-push-action@v4
#       with:
#         context: .
#         push: true
#         tags: ${{ steps.meta.outputs.tags }}
#         labels: ${{ steps.meta.outputs.labels }}
# 
#     - name: Trigger webhook
#       run: |
#         curl -X POST https://your-webhook-url.com \
#           -H "Content-Type: application/json" \
#           -d '{"repository": "${{ github.repository }}", "sha": "${{ github.sha }}"}'
